if(EXISTS "C:/Users/yoruk/Desktop/cen310-midterm-yoruk-ihsan/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
  include("C:/Users/yoruk/Desktop/cen310-midterm-yoruk-ihsan/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
