if(EXISTS "C:/Users/yoruk/Desktop/cen310-midterm-yoruk-ihsan/build_win/src/tests/calculator/calculator_tests[1]_tests.cmake")
  include("C:/Users/yoruk/Desktop/cen310-midterm-yoruk-ihsan/build_win/src/tests/calculator/calculator_tests[1]_tests.cmake")
else()
  add_test(calculator_tests_NOT_BUILT calculator_tests_NOT_BUILT)
endif()
